# Generated by Django 3.2 on 2022-06-11 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total expenses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message="balance can't be less than 0")], verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='app_users.buyerstatus', verbose_name='status'),
        ),
    ]
