# Generated by Django 3.2 on 2022-06-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='market',
        ),
        migrations.RemoveField(
            model_name='goodsmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itemcartmodel',
            name='goods',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total cost'),
        ),
        migrations.AddField(
            model_name='itemcartmodel',
            name='item_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_in_market', to='app_markets.itemgoodsmarketmodel', verbose_name='goods_in_market'),
        ),
        migrations.AddField(
            model_name='itemgoodsmarketmodel',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='itemgoodsmarketmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_history', to='app_markets.itemgoodsmarketmodel', verbose_name='goods')),
            ],
        ),
    ]
